[package]
name = "multi_auth_account"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v3.0.0-devnet.6-patch.1", directory = "aztec" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
